---
kind: pipeline
type: docker
name: Testing and building

steps:
  - name: install
    image: node
    commands:
      - npm ci

  - name: test
    when:
      branch:
        - master
        - develop
    image: node
    commands:
      - npm run test
  - name: build
    when:
      branch:
        - master
        - develop
    image: node
    commands:
      - npm run build
    environment:
      - APP_MODE:${DRONE_BRANCH}
