---
kind: pipeline
name: node6

steps:
  - name: test
    image: node:6
    commands:
      - npm install

---
kind: pipeline
name: node8

steps:
  - name: test
    image: node:8
    commands:
      - npm install
